In [2]:
import pandas as pd
import numpy as np
import urllib

from sqlalchemy import create_engine

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
server = r"DEVIL\SQLEXPRESS"
database = "ecommerce"

params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=" + params
)

print("SQL Server connection successful!")

SQL Server connection successful!

In [4]:
rfm_query = """
SELECT
    customer_unique_id,
    recency,
    frequency,
    monetary
FROM dbo.Customer_RFM
"""

rfm = pd.read_sql(
    rfm_query,
    engine
)

print("RFM Shape:", rfm.shape)

rfm.head()

c:\Users\sahuj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py:1649: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

RFM Shape: (93357, 4)

                 customer_unique_id  recency  frequency    monetary
0  0000366f3b9a7992bf8c76cfdf3221e2      111          1  141.899994
1  0000b849f77a49e4a4ce2b2a4ca5be3f      114          1   27.190001
2  0000f46a3911fa3c0805444483337064      537          1   86.220001
3  0000f6ccb0745a6a4b88665a16c9f078      321          1   43.619999
4  0004aac84e0df4da2b147fca70cf8255      288          1  196.889999

In [5]:
transactions_query = """
SELECT
    customer_unique_id,
    order_id,
    order_purchase_timestamp,
    total_order_value
FROM dbo.Customer_Transactions
"""

transactions = pd.read_sql(
    transactions_query,
    engine
)

transactions["order_purchase_timestamp"] = pd.to_datetime(
    transactions["order_purchase_timestamp"]
)

print("Transactions Shape:", transactions.shape)

transactions.head()

Transactions Shape: (96477, 4)

,customer_unique_id,order_id,order_purchase_timestamp,total_order_value
0,871766c5855e863f6eccc05f988b23cb,00010242fe8c5a6d1ba2dd792cb16214,2017-09-13 08:59:02,72.190002
1,eb28e67c4c0b83846050ddfb8a35d051,00018f77f2f0320c557190d7a144bdd3,2017-04-26 10:53:06,259.829987
2,3818d81c6709e39d06b2738a8d3a2474,000229ec398224ef6ca0657da4fc703e,2018-01-14 14:33:31,216.869995
3,af861d436cfc08b2c2ddefd0ba074622,00024acbcdf0a6daa1e931b038114c75,2018-08-08 10:00:35,25.780001
4,64b576fb70d441e8f1b2d7d446e483c5,00042b26cf59d7ce69dfabb4e55b4fd9,2017-02-04 13:57:51,218.039993

In [6]:
print(
    "First Order:",
    transactions["order_purchase_timestamp"].min()
)

print(
    "Last Order:",
    transactions["order_purchase_timestamp"].max()
)

First Order: 2016-10-03 09:44:50
Last Order: 2018-08-29 15:00:37

In [7]:
print("RFM rows:", len(rfm))
print("Transaction rows:", len(transactions))

print("\nRFM missing values:")
print(rfm.isnull().sum())

print("\nTransaction missing values:")
print(transactions.isnull().sum())

RFM rows: 93357
Transaction rows: 96477

RFM missing values:
customer_unique_id    0
recency               0
frequency             0
monetary              0
dtype: int64

Transaction missing values:
customer_unique_id          0
order_id                    0
order_purchase_timestamp    0
total_order_value           0
dtype: int64